version: "3"
services:
  web:
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/code # bind mount, this is workdir

      # this will create a empty volume which is nothing but
      # ignoring the node_modules for current service
      # https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder
      - /home/node/code/node_modules
    links:
      - db
    environment:
      MONGO_CONNECTION_STRING: mongodb://db:27017

  db:
    image: mongo:3
