version: "3.9"
services:
  web:
    build: ./
    image: logger/logger:latest
    container_name: logger #https://docs.docker.com/compose/compose-file/compose-file-v3/#container_name
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
