version: "3"
services:
  web:
    build: ./
    container_name: logger #https://docs.docker.com/compose/compose-file/compose-file-v3/#container_name
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
